import React, { useState, useEffect } from "react";
import { Modal, Select, Button, Typography, Space, Divider, Progress, Card, Spin, message } from "antd";
import axios from "axios";
import { RobotOutlined, CheckCircleOutlined } from "@ant-design/icons";

const { Title, Text, Paragraph } = Typography;
const { Option } = Select;

const SmartMatchModal = ({ visible, onClose, candidate }) => {
    const [jobs, setJobs] = useState([]);
    const [selectedJob, setSelectedJob] = useState(null);
    const [loadingMatch, setLoadingMatch] = useState(false);
    const [matchResult, setMatchResult] = useState(null);

    useEffect(() => {
        if (visible) {
            fetchJobs();
            setMatchResult(null);
            setSelectedJob(null);
        }
    }, [visible]);

    const fetchJobs = async () => {
        try {
            const res = await axios.get("http://localhost:5000/api/jobs");
            setJobs(res.data);
        } catch (err) {
            console.error("Failed to fetch jobs", err);
        }
    };

    const handleMatch = async () => {
        if (!selectedJob) {
            message.warning("Please select a job to match against");
            return;
        }

        setLoadingMatch(true);
        try {
            const job = jobs.find(j => j._id === selectedJob);
            const res = await axios.post("http://localhost:5000/api/ai/match", {
                cvText: `Candidate Name: ${candidate.name}\nSkills: ${candidate.skills?.join(", ")}\nExperience: ${candidate.experience || "N/A"}`,
                jobDescription: `Job Title: ${job.title}\nRequirements: ${job.description}\nSkills: ${job.skillsRequired?.join(", ")}`
            });
            setMatchResult(res.data.matchAnalysis);
        } catch (err) {
            message.error("AI Match failed");
            console.error(err);
        } finally {
            setLoadingMatch(false);
        }
    };

    // Helper to parse match score from AI text if possible
    const getScore = (text) => {
        const match = text?.match(/(\d+)\/100/);
        return match ? parseInt(match[1]) : 75; // Default to 75 if not found
    };

    return (
        <Modal
            title={<span><RobotOutlined /> AI Smart Match</span>}
            open={visible}
            onCancel={onClose}
            footer={[
                <Button key="back" onClick={onClose}>Close</Button>,
                <Button key="submit" type="primary" loading={loadingMatch} onClick={handleMatch}>
                    Analyze Match
                </Button>
            ]}
            width={700}
        >
            <div style={{ marginBottom: 20 }}>
                <Text strong>Candidate:</Text> <Text>{candidate?.name}</Text>
                <div style={{ marginTop: 8 }}>
                    <Text strong>Select Job to Match:</Text>
                    <Select
                        placeholder="Select a job"
                        style={{ width: '100%', marginTop: 8 }}
                        onChange={value => setSelectedJob(value)}
                    >
                        {jobs.map(job => (
                            <Option key={job._id} value={job._id}>{job.title} at {job.company}</Option>
                        ))}
                    </Select>
                </div>
            </div>

            <Divider />

            {loadingMatch ? (
                <div style={{ textAlign: 'center', padding: '40px' }}>
                    <Spin size="large" description="Cloudflare AI is analyzing the fit..." />
                </div>
            ) : matchResult ? (
                <Card>
                    <div style={{ textAlign: 'center', marginBottom: 20 }}>
                        <Title level={4}>Match Score</Title>
                        <Progress 
                            type="circle" 
                            percent={getScore(matchResult)} 
                            format={percent => `${percent}%`}
                            strokeColor={{
                                '0%': '#108ee9',
                                '100%': '#87d068',
                            }}
                        />
                    </div>
                    <Title level={5}>Analysis Details</Title>
                    <Paragraph style={{ whiteSpace: 'pre-wrap' }}>
                        {matchResult}
                    </Paragraph>
                    <div style={{ marginTop: 16, color: '#52c41a' }}>
                        <CheckCircleOutlined /> Recommendation generated by Cloudflare AI
                    </div>
                </Card>
            ) : (
                <div style={{ textAlign: 'center', color: '#8c8c8c', padding: '20px' }}>
                    Select a job and click "Analyze Match" to get AI insights.
                </div>
            )}
        </Modal>
    );
};

export default SmartMatchModal;
